version: '3.11.7'

services:
    api:
        container_name: fastapi_app
        build: api
        ports:
            - "8000:8000"
        command: gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker main:app
    
    redis:
        image: redis:7
        container_name: redis_app
        command: --port 5370
        expose:
        - 5370